"""OAuth user model name changed

Revision ID: 824ac7e075ad
Revises: a775dcd2b6f0
Create Date: 2025-03-07 20:18:20.310851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '824ac7e075ad'
down_revision: Union[str, None] = 'a775dcd2b6f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_model', sa.Column('test', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_model', 'test')
    # ### end Alembic commands ###
