"""OAuth user model name changed

Revision ID: a775dcd2b6f0
Revises: dbdddf2c69ed
Create Date: 2025-03-07 20:15:50.988595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a775dcd2b6f0'
down_revision: Union[str, None] = 'dbdddf2c69ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
