"""changed field name p_mail->email

Revision ID: a870c5d65b61
Revises: 59e8167a03a6
Create Date: 2025-03-03 20:05:15.610227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a870c5d65b61'
down_revision: Union[str, None] = '59e8167a03a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_model', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('user_model', 'p_mail')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_model', sa.Column('p_mail', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user_model', 'email')
    # ### end Alembic commands ###
